Repository auth0/auth0.net, pull requests merged in 2019-10, with the labels that each got.

#305 Prevent developers using IdentityTokenValidator directly
  LICENSE
  SECURITY-NOTICE.md
  build/common.props
  docs-source/docfx.json
  docs-source/filterConfig.yml
  docs/api/Auth0.AuthenticationApi.IdentityTokenValidator.html
  docs/api/Auth0.AuthenticationApi.html
  docs/api/toc.html
  docs/manifest.json
  docs/xrefmap.yml
  src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
  src/Auth0.AuthenticationApi/IdentityTokenValidator.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/IdentityTokenValidatorTests.cs
Labels: bug, security, small

#307 ClientBase now has initiate_login_uri property
  src/Auth0.ManagementApi/Models/ClientBase.cs
  tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
Labels: [Goalie] Review Required, small

#308 Miscellaneous cleanup
  src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
  src/Auth0.AuthenticationApi/Exceptions/IdentityTokenValidationException.cs
  src/Auth0.AuthenticationApi/IdentityTokenValidator.cs
  src/Auth0.Core/Http/ApiConnection.cs
  src/Auth0.ManagementApi/ManagementApiClient.cs
Labels: small
