Repository auth0/auth0.net, pull requests merged in 2020-10, with the labels that each got.

#429 [SDK-1822] Support new Email Verification Fields
  src/Auth0.ManagementApi/Models/EmailVerificationIdentity.cs
  src/Auth0.ManagementApi/Models/EmailVerificationTicketRequest.cs
  src/Auth0.ManagementApi/Models/VerifyEmailJobRequest.cs
  tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
  tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs
Labels: enhancement

#432 [SDK-2003] Support multiple Strategies in Connections.GetAllAsync
  src/Auth0.ManagementApi/Clients/ConnectionsClient.cs
  tests/Auth0.ManagementApi.IntegrationTests/ConnectionTests.cs
Labels: tiny

#425 Adds permission sources to User Response
  src/Auth0.ManagementApi/Clients/UsersClient.cs
  src/Auth0.ManagementApi/Models/PermissionSource.cs
  src/Auth0.ManagementApi/Models/PermissionSourceType.cs
  src/Auth0.ManagementApi/Models/UserPermission.cs
  tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs
Labels: enhancement, small

#437 Fix typo with AuthorizationCodeRequestBase
  src/Auth0.AuthenticationApi/Models/AuthorizationCodeRequestBase.cs
Labels: tiny

#438 [SDK-2005]: Complete passwordless API
  src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
  src/Auth0.AuthenticationApi/IAuthenticationApiClient.cs
  src/Auth0.AuthenticationApi/Models/PasswordlessEmailTokenRequest.cs
  src/Auth0.AuthenticationApi/Models/PasswordlessSmsTokenRequest.cs
  src/Auth0.AuthenticationApi/Models/PasswordlessTokenRequestBase.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
  tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs
Labels: CH: Added, medium
