Repository auth0/auth0.net, pull requests merged in 2021-03, with the labels that each got.

#477 Prepare project for Tenant Migration + RateLimit
  src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
  src/Auth0.ManagementApi/ManagementApiClient.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/AccessTokenTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/AuthenticationTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Builders/UriBuildersTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/DatabaseConnectionTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/HttpClientAuthenticationConnectionTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/PasswordlessTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Testing/TestHttpClientAuthenticationConnection.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Testing/TestHttpClientManagementConnection.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/IdTokenValidatorIntegrationTests.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Tokens/SymmetricSignedDecoderTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/BlacklistedTokensTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/BrandingClientTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/ClientGrantTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/ClientTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/ConnectionTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/CustomDomainsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/DeviceCredentialsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/EmailProviderTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/EmailTemplatesTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/HooksTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/HttpClientManagementConnectionTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/JobsTest.cs
  tests/Auth0.ManagementApi.IntegrationTests/LoadTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/LogStreamsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/LogsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/ResourceServerTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/RolesTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/RulesTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/StatsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/TestBase.cs
  tests/Auth0.ManagementApi.IntegrationTests/Testing/TestHttpClientAuthenticationConnection.cs
  tests/Auth0.ManagementApi.IntegrationTests/Testing/TestHttpClientManagementConnection.cs
  tests/Auth0.ManagementApi.IntegrationTests/TicketsTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/UserBlockTests.cs
  tests/Auth0.ManagementApi.IntegrationTests/UsersTests.cs
Labels: large

#480 Add ApiError to RateLimitException to access the response body
  src/Auth0.Core/Exceptions/ApiException.cs
  src/Auth0.Core/Exceptions/RateLimitApiException.cs
  tests/Auth0.Core.UnitTests/ApiErrorDeserializationTests.cs
  tests/Auth0.Core.UnitTests/RateLimitApiExceptionTests.cs
Labels: CH: Changed

#482 Change Guardian Factors test to expect 7 instead of 6 factors
  tests/Auth0.ManagementApi.IntegrationTests/GuardianTests.cs
Labels: review:tiny

#485 Release 7.6.1
  CHANGELOG.md
  build/common.props
  docs/api/Auth0.AuthenticationApi.AuthenticationApiClient.html
  docs/api/Auth0.Core.Exceptions.RateLimitApiException.html
  docs/api/Auth0.ManagementApi.ManagementApiClient.html
  docs/xrefmap.yml
Labels: review:small

#486 [SDK-2400] Add support for Organizations
  docs-source/index.md
  src/Auth0.AuthenticationApi/AuthenticationApiClient.cs
  src/Auth0.AuthenticationApi/Builders/AuthorizationUrlBuilder.cs
  src/Auth0.AuthenticationApi/Models/AuthorizationCodeRequestBase.cs
  src/Auth0.AuthenticationApi/Models/RefreshTokenRequest.cs
  src/Auth0.AuthenticationApi/Tokens/Auth0ClaimNames.cs
  src/Auth0.AuthenticationApi/Tokens/IdTokenClaimValidator.cs
  src/Auth0.AuthenticationApi/Tokens/IdTokenRequirements.cs
  tests/Auth0.AuthenticationApi.IntegrationTests/Builders/UriBuildersTests.cs
Labels: review:medium

#487 Release 7.7.0
  CHANGELOG.md
  build/common.props
  docs/api/Auth0.AuthenticationApi.Builders.AuthorizationUrlBuilder.html
  docs/api/Auth0.AuthenticationApi.Models.AuthorizationCodePkceTokenRequest.html
  docs/api/Auth0.AuthenticationApi.Models.AuthorizationCodeRequestBase.html
  docs/api/Auth0.AuthenticationApi.Models.AuthorizationCodeTokenRequest.html
  docs/api/Auth0.AuthenticationApi.Models.RefreshTokenRequest.html
  docs/index.html
Labels: review:small

#488 Add organization to XML Docs
  src/Auth0.AuthenticationApi/Tokens/IdTokenRequirements.cs
Labels: review:tiny
