Repository auth0/auth0.net, pull requests merged in 2021-02, with the labels that each got.

#468 Update Docs for GetUsersRequest regarding Connection and SearchEngine
  src/Auth0.ManagementApi/Models/GetUsersRequest.cs
Labels: docs, review:tiny

#467 Sync Tenant Flags with API v2
  src/Auth0.ManagementApi/Models/TenantFlags.cs
  tests/Auth0.ManagementApi.IntegrationTests/TenantSettingsTests.cs
Labels: CH: Changed, review:small

#469 Prepare 7.5.1
  CHANGELOG.md
  build/common.props
  docs/api/Auth0.ManagementApi.Models.GetUsersRequest.html
  docs/api/Auth0.ManagementApi.Models.PasswordChangeTicketRequest.html
  docs/api/Auth0.ManagementApi.Models.TenantFlags.html
  docs/api/Auth0.ManagementApi.Models.html
  docs/manifest.json
  docs/xrefmap.yml
Labels: review:small

#471 Hooks
  src/Auth0.ManagementApi/Clients/HooksClient.cs
  src/Auth0.ManagementApi/ManagementApiClient.cs
  src/Auth0.ManagementApi/Models/GetHooksRequest.cs
  src/Auth0.ManagementApi/Models/Hook.cs
  src/Auth0.ManagementApi/Models/HookBase.cs
  src/Auth0.ManagementApi/Models/HookCreateRequest.cs
  src/Auth0.ManagementApi/Models/HookUpdateRequest.cs
  tests/Auth0.ManagementApi.IntegrationTests/HooksTests.cs
Labels: CH: Added

#473 Use .NET 5 for test projects
  tests/Auth0.AuthenticationApi.IntegrationTests/Auth0.AuthenticationApi.IntegrationTests.csproj
  tests/Auth0.Core.UnitTests/Auth0.Core.UnitTests.csproj
  tests/Auth0.ManagementApi.IntegrationTests/Auth0.ManagementApi.IntegrationTests.csproj
Labels: review:tiny

#474 Ensure await is using ConfigureAwait
  src/Auth0.AuthenticationApi/Tokens/IdTokenValidator.cs
  src/Auth0.AuthenticationApi/Tokens/JsonWebKeys.cs
  src/Auth0.Core/Exceptions/ApiException.cs
Labels: CH: Changed, review:small

#472 [SDK-2297] Add playground applications for .NET 5, .NET Core 3.1 and .NET Framework
  Auth0.Net.sln
  azure-pipelines.yml
  playground/Auth0.NET5/Auth0.NET5.csproj
  playground/Auth0.NET5/Controllers/ClientsController.cs
  playground/Auth0.NET5/Program.cs
  playground/Auth0.NET5/Properties/launchSettings.json
  playground/Auth0.NET5/Startup.cs
  playground/Auth0.NET5/appsettings.Development.json
  playground/Auth0.NET5/appsettings.json
  playground/Auth0.NETCore3/Auth0.NETCore3.csproj
  playground/Auth0.NETCore3/Controllers/ClientsController.cs
  playground/Auth0.NETCore3/Program.cs
  playground/Auth0.NETCore3/Properties/launchSettings.json
  playground/Auth0.NETCore3/Startup.cs
  playground/Auth0.NETCore3/appsettings.Development.json
  playground/Auth0.NETCore3/appsettings.json
  playground/Auth0.NETFramework/App_Start/FilterConfig.cs
  playground/Auth0.NETFramework/App_Start/WebApiConfig.cs
  playground/Auth0.NETFramework/Auth0.NETFramework.csproj
  playground/Auth0.NETFramework/Controllers/ClientsController.cs
  playground/Auth0.NETFramework/Global.asax
  playground/Auth0.NETFramework/Global.asax.cs
  playground/Auth0.NETFramework/Properties/AssemblyInfo.cs
  playground/Auth0.NETFramework/Web.Debug.config
  playground/Auth0.NETFramework/Web.Release.config
  playground/Auth0.NETFramework/Web.config
Labels: review:medium

#476 Release 7.6.0
  CHANGELOG.md
  build/common.props
  docs/api/Auth0.ManagementApi.Clients.BaseClient.html
  docs/api/Auth0.ManagementApi.Clients.BrandingClient.html
  docs/api/Auth0.ManagementApi.Clients.HooksClient.html
  docs/api/Auth0.ManagementApi.Clients.html
  docs/api/Auth0.ManagementApi.ManagementApiClient.html
  docs/api/Auth0.ManagementApi.Models.Branding.html
  docs/api/Auth0.ManagementApi.Models.BrandingBase.html
  docs/api/Auth0.ManagementApi.Models.BrandingColors.html
  docs/api/Auth0.ManagementApi.Models.BrandingFont.html
  docs/api/Auth0.ManagementApi.Models.BrandingUpdateRequest.html
  docs/api/Auth0.ManagementApi.Models.GetHooksRequest.html
  docs/api/Auth0.ManagementApi.Models.Hook.html
  docs/api/Auth0.ManagementApi.Models.HookBase.html
  docs/api/Auth0.ManagementApi.Models.HookCreateRequest.html
  docs/api/Auth0.ManagementApi.Models.HookUpdateRequest.html
  docs/api/Auth0.ManagementApi.Models.UniversalLoginTemplate.html
  docs/api/Auth0.ManagementApi.Models.UniversalLoginTemplateUpdateRequest.html
  docs/api/Auth0.ManagementApi.Models.html
  docs/api/toc.html
  docs/manifest.json
  docs/xrefmap.yml
Labels: medium
